bank_sync:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: actualbudget

budget_sync:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: actualbudget

akahu_bank_sync:
  fields:
    sync_days:
      required: false
      description: "Number of days to sync, or 'ALL' for max available"
      selector:
        text:
    sync_categories:
      required: false
      description: "Choose whether to allow auto syncing of categories from bank transactions in to Actual"
      selector:
        boolean:
          default: false
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: actualbudget
